### ISSUE TITLE
Add -firstrun environment variable 

### ISSUE THREAD

**Issue by ArtificialTruth** [hallowelt/docker-bluespice-free#1]
First of all, thank you for creating this excellent Docker image. 
I would like to suggest an improvement for this image.
_Disclaimer: I am new to Docker, so the following suggestion may not be in line with best pratices._

**Current situation:** 
When a container is created based on the bluespice/bluespice-free image, the init.sh script will setup the wiki for the first time ([if the .firstrun file exists](https://github.com/hallowelt/docker-bluespice-free/blob/master/includes/init/init.sh#L3))
If you want to [keep your data outside of the docker](https://github.com/hallowelt/docker-bluespice-free/blob/master/README.md#keep-your-data-outside-of-the-docker) (persistent storage) you can use the -v option
Then you can change LocalSettings.php, add some pages in the wiki etc easily. When the container is stopped and removed, the data will stay. 

**Complication:**
When creating a new container (from same image, or perhaps future image) BlueSpice will install the wiki and overwrite the contents that is mounted with -v, thus loosing any changes made to LocalSettings.php etc.

**Question:**
How can we create a new container that uses the same data & configs made by previous containers, without overwriting the configs with the defaults?

**Suggestion:**
Create a new enviroment variable `"firstrun=false"`, if set to false, [this line](https://github.com/hallowelt/docker-bluespice-free/blob/master/Dockerfile#L15) will not run in the Dockerfile, and thus no `"/opt/docker/.firstrun"` file is created

Eg run the container with:
`docker run -d -p 80:80 -v {/my/data/folder}:/data -e "firstrun=false" "bs_lang=en" -e "bs_url=http://www.domain.com" bluespice/bluespice-free`

**Comment by gokhangeyik** [comment]
Hello,

Thank you for your feedback and detailed explanation. 
The selective `firstrun` idea is actually great. We don't need to discuss it even.
I will implement this as soon as possible.

**Comment by ArtificialTruth** [comment]
Thank you! Have a great day!

**Comment by gokhangeyik** [comment]
Hello,

I made the required changes but at the same time, I want to keep it simple. So we don't need to define any environment variable for it. Basically `init.sh` will understand existing installations.

`init.sh` will gonna check `/data/mysql` folder existence and also `/data/www/bluespice/w/LocalSettings.php` file existence.
In this case, the script will try to migrate current data to the new installation.
Old files will be left at `/data/www/bs_old`.

I have not released this one on the docker hub yet. I need more tests.
If you can find time for the test, I will be so happy.

Thank you very much.

**Comment by gokhangeyik** [comment]
A new version is released (3.1.3)
With this new version, the Docker image will understand the current installation.

Thank you for your contribution.

**Comment by ArtificialTruth** [comment]
Hi @gokhangeyik 

Thank you very much for your support. I have not had the time to test it out, but I greatly appriciate your work.

Have a wonderful week!
