### ISSUE TITLE
Nginx, wiki won't work if port isn't 80 or 443

### ISSUE THREAD

**Issue by otheus** [hallowelt/docker-bluespice-free#2]
Nginx uses the standard ports as hard-coded value when doing a redirect, instead of the user-supplied ones. Apparently, mediawiki/bluespice is doing this too, for instance, on the login screen.

It's necessary to fix this in docker because you cannot guarantee the service will be accessible to the user via the ports 80 and 443. They may be mapped to other ports (and probably will be if run in any kind of production environment). 

Here is a fix for the nginx/bluespice.conf file:

```
diff --git a/includes/misc/nginx/bluespice.conf b/includes/misc/nginx/bluespice.conf
index 74f8e83..50bdf9e 100644
--- a/includes/misc/nginx/bluespice.conf
+++ b/includes/misc/nginx/bluespice.conf
@@ -32,7 +32,7 @@ server {
        location = /robots.txt {
        }
        location = / {
-               return 301 http://$host/wiki$request_uri;
+               return 301 $scheme://$http_host/w/index.php;
        }
        location ~ \.php {
         include fastcgi.conf;
```

**Comment by otheus** [comment]
OK, so some support for this exists. And I guess my situation is a tad unusual. Something else needs port 80 on my laptop. In our production clusters, we would have proxies, but the user will typically see the standard ports. However, for development, an alternate port might be used. 

It looks like in some cases, bluespice will try to contact itself on a particular port. that port might be different than the one the users must use. For instance: in `./bluespice/maintenance/dev/installmw.sh` and related `$PORT` is used.
One problem is the `./LocalSettings.php` generated after install, which contains
```
$wgServer = "http://localhost";
```
It should be:
```
$wgServer = $_SERVER["REQUEST_SCHEME"]."//".$_SERVER["HTTP_HOST"];
```
Unfortunatley, this will cause maintenance scripts to choke, so we must be a little smarter:
```
$wgServer = ($_SERVER["REQUEST_SCHEME"] ?? "http")."://".($_SERVER["HTTP_HOST"] ?? "localhost"); 
```

(Note: this solution works here, but in php-fpm or proxied scenarios, we need to get the HTTP_HOST value from X-Forwarded-For and SCHEME. Older versions of PHP < 7, Apache (<2.4) and Nginx (<2016) don't support REQUEST_SCHEME). 


However, I noticed that `init.sh` contains some other code:
```
        if [ -z $bs_url ]; then
            bs_url="http://localhost";
        fi
```
which is invoked with  `/usr/bin/php /data/www/bluespice/w/maintenance/install.php ...-server=`

Even if those scripts simply shove the string as-si into the the `$wgServer` setting, you have a quoting problem. Thus, we need to look at install.php and this init script as well. But since I don't know where these come from (MediaWiki? BlueSpice), I'm loathe to touch them. A post-install `sed` script could be used instead.

**Comment by otheus** [comment]
Here is my *locally-tested* solution to the last problem.  ~("locally-tested" -- ie, in situ with sed, but not within a new docker instance).~  A docker rebuild and initial test indicates everything works as expected. I changed port numbers and stuff continues to work. (Again, maintenance scripts will be an issue.)

```diff
diff --git a/includes/init/init.sh b/includes/init/init.sh
index 082a944..16261f4 100644
--- a/includes/init/init.sh
+++ b/includes/init/init.sh
@@ -27,7 +27,7 @@ if [ -f "/opt/docker/.firstrun" ]; then
             bs_lang="en"
         fi
         if [ -z $bs_url ]; then
-            bs_url="http://localhost";
+            bs_url="WGSERVER_HACKME";
         fi
         if [ -z $bs_user ]; then
             bs_user="WikiSysop";
@@ -44,6 +44,7 @@ if [ -f "/opt/docker/.firstrun" ]; then
         fi
         echo "Installing BlueSpice..."
         /usr/bin/php /data/www/bluespice/w/maintenance/install.php --confpath="/data/www/bluespice/w" --dbname="bluespice" --dbuser="bluespice" --dbpass="$rndpass" --dbserver="localhost" --lang="$bs_lang" --pass="$bs_password" --scriptpath=/w --server="$bs_url" "BlueSpice" "$bs_user" > /dev/null 2>&1
+       sed  -i .bak '/^$wgServer/s/"WGSERVER_HACKME"/($_SERVER["REQUEST_SCHEME"] ?? "http").":\/\/".($_SERVER["HTTP_HOST"] ?? "localhost")/' /data/www/bluespice/w/LocalSettings.php
         ln -s /opt/docker/bluespice-data/settings.d/* /data/www/bluespice/w/settings.d/
         mkdir -p /data/www/bluespice/w/extensions/BlueSpiceFoundation/data > /dev/null 2>&1
         mkdir -p /data/www/bluespice/w/extensions/BlueSpiceFoundation/config > /dev/null 2>&1
```

**Comment by Jonty16117** [comment]
resolving this issue in: https://github.com/hallowelt/docker-bluespice-free/pull/22

**Comment by Jonty16117** [comment]
this issue should be resolved now

**Comment by Jonty16117** [comment]
is linked to: https://github.com/hallowelt/docker-bluespice-free/issues/8 therefore marking it resolved
