### ISSUE TITLE
search does not work

### ISSUE THREAD

**Issue by atar-axis** [hallowelt/docker-bluespice-free#31]
using the master, the search does not work. it does not display anything and is loading forever.

![image](https://github.com/hallowelt/docker-bluespice-free/assets/11148588/18e1cc16-77bf-4a38-b087-0f25d2b3156a)

**Comment by Jonty16117** [comment]
can you show docker logs using: `docker logs container name or id`

**Comment by Jonty16117** [comment]
just a note, you must be logged in before using the search

**Comment by Jonty16117** [comment]
stale issue, also the local tests confirm the search is working
